### ISSUE TITLE
Error installing package.

### ISSUE THREAD

**Issue by KannanRams** [ngneat/dialog#2]
An unhandled exception occurred: Collection "@ngneat/dialog" cannot be resolved.

[error] Error: Collection "@ngneat/dialog" cannot be resolved.
    at NodeModulesEngineHost._resolveCollectionPath (D:\Libraries\Documents\Angular\BStarter\CrewClient\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:91:15)
    at NodeModulesEngineHost.createCollectionDescription (D:\Libraries\Documents\Angular\BStarter\CrewClient\node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:115:27)
    at SchematicEngine._createCollectionDescription (D:\Libraries\Documents\Angular\BStarter\CrewClient\node_modules\@angular-devkit\schematics\src\engine\engine.js:147:40)
    at SchematicEngine.createCollection (D:\Libraries\Documents\Angular\BStarter\CrewClient\node_modules\@angular-devkit\schematics\src\engine\engine.js:140:43)
    at AddCommand.getCollection (D:\Libraries\Documents\Angular\BStarter\CrewClient\node_modules\@angular\cli\models\schematic-command.js:128:35)
    at AddCommand.runSchematic (D:\Libraries\Documents\Angular\BStarter\CrewClient\node_modules\@angular\cli\models\schematic-command.js:291:50)
    at AddCommand.executeSchematic (D:\Libraries\Documents\Angular\BStarter\CrewClient\node_modules\@angular\cli\commands\add-impl.js:148:31)
    at AddCommand.run (D:\Libraries\Documents\Angular\BStarter\CrewClient\node_modules\@angular\cli\commands\add-impl.js:114:21)
    at async AddCommand.validateAndRun (D:\Libraries\Documents\Angular\BStarter\CrewClient\node_modules\@angular\cli\models\command.js:134:28)
    at async Object.runCommand (D:\Libraries\Documents\Angular\BStarter\CrewClient\node_modules\@angular\cli\models\command-runner.js:186:24)
    at async default_1 (D:\Libraries\Documents\Angular\BStarter\CrewClient\node_modules\@angular\cli\lib\cli\index.js:54:31)

**Comment by NetanelBasal** [comment]
Can you provide more details, please?

**Comment by KannanRams** [comment]
Thanks for your reply. 
Pls. ignore it, was trying to add in Ang. version 8 project.
It works after upgrading to ver 9
